const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const html=fs.readFileSync('index.html','utf8');
function fn(from,to){return html.slice(html.indexOf(from),html.indexOf(to,html.indexOf(from)));}
function sandbox(response){const context={Date,DB:{verifyGcashReceipt:async()=>response},setBookingReceiptUploadMessage(){},bookingReceiptUploadReady:()=>false};vm.createContext(context);vm.runInContext(fn('function isBdoRcbcRejectedReceipt(', 'function sendCustomerConfirmationEmail(')+fn('function normalizeStoredBookingReceipt(', 'async function recoverStoredBookingReceipt('),context);return context;}
const extracted={provider:'rcbc',rcbc:{sourceParserVersion:'bdo_to_rcbc_v1'}};
test('BDO RCBC duplicate response is rejected in customer view',async()=>{const c=sandbox({status:'rejected',extracted,receiptImageUrl:'private/test',publicReason:'Duplicate invoice rejected'});const r=await c.verifyUploadedReceipt('TEST','rcbc',null,{type:'image/png'});assert.equal(r.status,'rejected');assert.equal(r.bookingStatus,'cancelled');assert.equal(r.paymentStatus,'rejected');assert.equal(r.message,'Duplicate invoice rejected');});
test('BDO RCBC saved rejection survives recovery after a lost response',()=>{const c=sandbox({});const r=c.normalizeStoredBookingReceipt({receipt_image_url:'private/test',receipt_status:'rejected',receipt_extracted:extracted,status:'cancelled',payment_status:'rejected'});assert.equal(r.status,'rejected');assert.equal(r.bookingStatus,'cancelled');});
test('other routes retain manual review behavior',async()=>{for(const source of ['gotyme_to_rcbc_v1','bpi_to_rcbc_v1','bdopay_to_gcash_v1']){const c=sandbox({status:'rejected',extracted:{provider:'rcbc',rcbc:{sourceParserVersion:source}},receiptImageUrl:'private/test'});assert.equal((await c.verifyUploadedReceipt('TEST','rcbc',null,{type:'image/png'})).status,'manual_review');}});
test('BDO uncertainty remains pending; approval preserves server payment status',async()=>{for(const status of ['manual_review','auto_approved']){const c=sandbox({status,extracted,receiptImageUrl:'private/test',paymentStatus:'paid',bookingStatus:'confirmed'});const r=await c.verifyUploadedReceipt('TEST','rcbc',null,{type:'image/png'});assert.equal(r.status,status);assert.equal(r.paymentStatus,status==='auto_approved'?'paid':'for_verification');}});
